### ISSUE TITLE
isLoading

### ISSUE THREAD

**Issue by nicolasbonnetdu13** [jmgueirard/MartialApp#1]
Mec j'ai trouvé ca hier. C'est grave stylé ^^

readonly ObservableAsPropertyHelper<bool> _isLoading;
public bool IsLoading
{
	get { return _isLoading.Value; }
}

Dans le constructeur de la ViewModel
LoginCommand.IsExecuting.ToProperty(this, x => x.IsLoading, out _isLoading);

En gros avec ca tu n'as plus besoin de te soucier du isLoading =)

**Comment by jmgueirard** [comment]
Yep j'ai refactoré ça :) merci
